### ISSUE TITLE
Deploy fails - doesn't ask you for a password

### ISSUE THREAD

**Issue by blackpond** [net-ssh/net-ssh#145]
servers: ["**_.**_.**_.**_"]
**\* [deploy:update_code] rolling back
- executing "rm -rf /home/deploy/giftlift/releases/20140209033514; true"
  servers: ["888.**_.**_.**_.**_"]
  *\* [deploy:update_code] exception while rolling back: Capistrano::ConnectionError, connection failed for: **_.**_.**_.**_ (Net::SSH::AuthenticationFailed: Authentication failed for user

http://stackoverflow.com/questions/21560297/capistrano-sshauthenticationfailed-not-prompting-for-password

**Comment by shkkmo** [comment]
This issue is solved for me (sort of) with net-ssh-2.9.2.rc1

While net-ssh is now prompting me for a password, it is still ignoring the ':password' parameter that is being passed in from capistrano. In 2.7 the ':password' parameter is used correctly, and the connection works without net-ssh prompting me.

Summary:
2.7.0 works
2.8.0 - 2.9.1 fails
2.9.2.rc1 prompts for password but ignores the password parameter it was accepting in 2.7.0

Has their been a change to your API? Or should there be a new issue created for this?

**Comment by mfazekas** [comment]
@shkkmo what is you capistrano version, what is the config for setting password?

**Comment by shkkmo** [comment]
I'm running Capistrano v2.15.5 and Capifony and the password is set (basically) using:

```javascript
set :password, Capistrano::CLI.password_prompt("Enter SSH Password: ") {|q| q }
```

I believe the password parameter is from capistrano and is not capifony specific, but I'm not sure.

I have looking this on my list: https://github.com/capistrano/symfony and will just stay with 2.7 until I have the time to migrate our existing deployment recipes over to it.

**Comment by mfazekas** [comment]
Specifying a password in config seems to work in capistrano 3, but not in capistrano 2.
So basically capistrano 2 logic is to first try without password, if it's succeeds then retries with password from the config.

Since capistrano2 no longer maintained. I see the following options for capistrano2 users with password:
   * stick with 2.7.0
   * use 2.9.1 with ```set :ssh_options, { config: false}```
   * use 2.9.2 but remove the your prompt for password as net-ssh will ask for that

See:
https://github.com/capistrano/capistrano/blob/legacy-v2/lib/capistrano/ssh.rb#L50
https://github.com/capistrano/capistrano/blob/legacy-v2/lib/capistrano/ssh.rb#L81

```
password_value = nil
...
begin
  connection_options = ssh_options.merge(
    :password => password_value,
    :auth_methods => ssh_options[:auth_methods] || methods.shift
  )

  yield host, user, connection_options
rescue Net::SSH::AuthenticationFailed
  raise if methods.empty? || ssh_options[:auth_methods]
  password_value = options[:password]
  retry
end
```

**Comment by Startouf** [comment]
I've tried a lot of stuff I found on the internet, but I still can't get it to work, neither with public key nor with password.

    SSHKit::Runner::ExecuteError: [...]
    Net::SSH::AuthenticationFailed: Authentication failed for user

    capistrano 3.3.3
    ssh-kit 1.6.1
    net-ssh 2.9.1

I can successfully connect using SSH with my key stored in my ssh-agent, but from capistrano even with your `config: false`, it doesn't work.

Also I tried using ssh-doctor...
I added `require 'capistrano/ssh_doctor` on top of my Capfile, but running `sudo cap test ssh:doctor` doesn't seem to be working (doesn't generate a report, still the same error AuthFailed)

**Comment by mfazekas** [comment]
@Startouf i think your issue is unrelated this thread is about Capistrano 2 not asking for password. Can you try with 2.9.2.rc1, also can you enable verbose log, and open a new report if the issue still persist?
