### ISSUE TITLE
Net::SSH::Proxy::Command does not work with '%r' ssh_config ProxyCommand

### ISSUE THREAD

**Issue by yasir091** [net-ssh/net-ssh#189]
Hi,
  I am running on mac OS X 10.9.4, for me it is failing on 

/Users/yasaleem/.rvm/gems/ruby-2.1.2/gems/net-ssh-2.9.1/lib/net/ssh/proxy/command.rb:48

I am not sure where ':remote_user' is set or coming from. Isn't that should be ':user' ? - When I change to that value means the line looked like

remote_user = connection_options && connection_options[:user]

It worked for me.

My stack trace is shown below:

remote user name not available (ArgumentError)
/Users/yasaleem/.rvm/gems/ruby-2.1.2/gems/net-ssh-2.9.1/lib/net/ssh/proxy/command.rb:48:in `block in open'
/Users/yasaleem/.rvm/gems/ruby-2.1.2/gems/net-ssh-2.9.1/lib/net/ssh/proxy/command.rb:37:in `gsub'
/Users/yasaleem/.rvm/gems/ruby-2.1.2/gems/net-ssh-2.9.1/lib/net/ssh/proxy/command.rb:37:in `open'
/Users/yasaleem/.rvm/gems/ruby-2.1.2/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:69:in `block in initialize'
/Users/yasaleem/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/Users/yasaleem/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
/Users/yasaleem/.rvm/gems/ruby-2.1.2/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize'
/Users/yasaleem/.rvm/gems/ruby-2.1.2/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `new'
/Users/yasaleem/.rvm/gems/ruby-2.1.2/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `start'

Thanks,
Yasir.

**Comment by dominics** [comment]
According to the original merge (https://github.com/net-ssh/net-ssh/pull/139#issuecomment-35518045), the option should be `remote_user`, not `user`. (Just guessing, but one could be the user on the proxy host, the other the user on the far side of the proxy.)

As noted in that PR, though, it wasn't added to `VALID_OPTIONS` (because there was no test case to check whether that was a problem?! I don't think the original feature should have been merged if there was no way to actually use it.)
