### ISSUE TITLE
Open channel feature is not thread-safe

### ISSUE THREAD

**Issue by TiagoCardoso1983** [net-ssh/net-ssh#302]
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/connection/session.rb#L482-L484

I was under the assumption that opening channels would be thread-safe. 

My idea is: let separate threads open channels and wait on them, while a main thread loop on the connection. 

Which leads me to the question; how to efficiently loop forever on a connection? From what I read, calling  connection.loop will block until there's nothing more to read/write. How to effectively listen on events in channels so one can loop again?

**Comment by mfazekas** [comment]
I'm not sure why you'd want use channels on the same connection from different threads. You should be able to implement this on top of net-ssh. Just process event in the main thread then pass it to the per channel thread.

There are some looping constructs defined on session, not sure what you mean by ```efficiently loop forever on a connection```

https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/connection/session.rb#L173
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/connection/session.rb#L151

**Comment by TiagoCardoso1983** [comment]
Forget the last part, I was confused by the API. One can just wait on the channel after acquiring it. 

My use case is this main worker process, where I have to run certain commands on the same server. Rate-limit the load by number of workers (the commands might take time), each running in its own thread (it's sidekiq). On process init, I eager-load an SSH connection. After that, jobs are as follows: acquire channel from centralized connection, define callbacks, wait on channel. It works well in "in my machine" :) .

My main issue with this is that opening channels is not thread-safe. I don't know anymore if it should be designed in that way, maybe I can just synchronize access to the centralized connection when doing it. Which might just be ok.

**Comment by mikecmpbll** [comment]
I feel like I'm in a similar situation, so I thought I'd ask here (sorry if it's a bit long-winded).

I have a load of commands that I need to execute, determined at runtime, over an SSH connection. I want to take advantage of the parallelism that channels affords me. I cannot just `exec` them all at once and then loop, because any more than 10 channels I get a error, so I've created a little wrapper with a queue and it execs 10, loops, execs 10, loops, etc.

I've two problems with this approach:

1) I have to wait for all 10 to finish before I can issue another command (which isn't very efficient of one command takes much longer than all the others)
2) I'm getting `Net::SSH::ChannelOpenFailed: open failed (1)` at random points even though I'm staying within the channel limit :/ (I don't fully understand this, probably something to do with my code)

Is there an established approach for doing this sort of thing? Could I keep the loop running in a separate thread and open the channels in the main thread?

**Comment by mfazekas** [comment]
@mikecmpbll i don't think it's related, and i don't think threads would help you much. 
I think a queue is a great idea. I'd execute items form queu until i get an error on open. If i get an error on open i'd put command back to queue, and wait for channel close before trying next one.

**Comment by mikecmpbll** [comment]
Hmpf, still struggling a bit. I can't see how to avoid using threads because the ssh.loop blocks, so I cannot open a channel while it's processing any already opened channels? I want to maintain 10 busy channels until all the commands have been executed. I have tried this:

```ruby
q = Queue.new
ssh = Net::SSH.start(...)

ssh_loop = Thread.new do
    loop do
      ssh.loop
      sleep 1
    end
  end

q_loop = Thread.new do
    loop do
      if ssh.channels.count >= 9
        sleep(1) and next
      end
      j = q.pop
      ssh.open_channel{ |ch| j.call(ch) }
    end
  end

100.times { q.push ->(ch) { ch.exec("echo 'foo'") } }
```

The queue thread will open the channel if there's fewer than 10 channels already, or wait until there is, and the ssh thread just keeps looping on it. It seems to work quite nice actually .. the issue is that I intermittently hit:

    /home/deploy/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:306:in `open_channel': can't add a new key into hash during iteration (RuntimeError)

**Comment by TiagoCardoso1983** [comment]
@mikecmpbll , my workaround:

```ruby
#singleton with a connection
class Connector
  def initialize
    @lock = Mutex.new
    @ssh = Net::SSH.start(....)
  end
 
  # protect channel acquisition
  def acquire_channel(&on_channel)
    @lock.synchronize do
      @ssh.open_channel(&on_channel)
     end
  end
end

# everywhere else, access the connector object and roll

Thread.new do # or inside a threaded worker like sidekiq
  $connection.acquire_channel do |ch|
     ch.exec(...) do ...
       # send command, define handlers, etc
     end
     ch.wait
  end
end

```

You don't need to call loop yourself, Channel#wait will loop until the channel is closed.

**Comment by mfazekas** [comment]
I was thinking on something like this - this is more a draft than a working solution: 
```ruby
q = Queue.new
ssh = Net::SSH.start(...)

class Executor
  def initialize
     @failed = nil
  end 
  def execute(ssh,q)
    j = @failed || q.pop
    ssh.open_channel do |ch|
       ch.on_open_failed { |ch,code,desc| @failed = j }
       ch.on_channel_close { |ch| self.execute(ssh,q) } 
       j.call(ch)
    end
  end
end

100.times { q.push ->(ch) { ch.exec("echo 'foo'") } }
executor = Executor.new
10.times { executor.execute(ssh,q) }
```

Not sure if this works as ```on_channel_close``` likely will be called when the channel is still open.

**Comment by mikecmpbll** [comment]
@mfazekas : I thought of something a bit like this while I've been playing around, I gave it a go but encountered the problem that you mentioned at the bottom—would work if there was an after_channel_close hook. I might try hack something together this evening.

@TiagoCardoso1983 : thanks! I now realise that our problems are slightly different but that's useful nonetheless.

**Comment by mikecmpbll** [comment]
I was wrong, the on_close hook happens after channel close, I'm not sure what problem I was experiencing before! I've ended up with this, based from @mfazekas's example (this is a runnable example):

```ruby
require 'net/ssh'
require 'thread'

class Executor
  attr_accessor :ssh, :q, :failed, :channels

  def initialize(ssh)
    @failed   = Queue.new
    @q        = Queue.new
    @ssh      = ssh
    @channels = []
  end

  def execute
    channels << Thread.new do
      j = (@failed.pop(true) rescue nil) || q.pop
      c = ssh.open_channel do |ch|
        ch.on_close { self.execute }
        j.call(ch)
      end
      c.on_open_failed{ |ch, code, desc| @failed.push(j) }
    end
  end
end

# put your ssh stuff in here!
ssh = Net::SSH.start(...) 
e = Executor.new(ssh)
# start a runner thread to loop the ssh forever
runner = Thread.new{ e.ssh.loop(1){ true } }
# start 8 threads waiting on the queue, ready to open 8 channels
8.times{ e.execute }
# add a bunch of jobs
200.times do |i|
  # push to the executor's job queue
  e.q.push(->(ch) do
    ch.exec("echo 'foo#{i}'") do |ch, s|
      # callback so we can see our commands returning data
      ch.on_data{ |ch, d| puts d }
    end
  end)
end

# wait till finished
sleep(1) while e.ssh.busy? || !e.q.empty?

# close up
e.ssh.close

**Comment by Marcofeli** [comment]
Hi, I have a similar problem and maybe you could help me to find out what's happening here. I'm trying to execute two commands at the same time using different threads and different channels. The thing is that I execute a command that takes too much time to be terminated, for that reason (even using the keepalive feature) the process gets stuck waiting for a response. Even when the command is terminated on the remote host the channel appears to not realize of it, so it keeps blocked. So I'm trying the following:

1.  Execute the "large command" on a thread, using an already started ssh session to create the channel
2.  Starting a loop which checks the status of the "large command" every 5 seconds by running another command in a different channel, also created using the same ssh session
3.  If the command was succesfully executed stop the loop, else keep checking the status by using the "check status command"

Now it gets weird, sometimes it works perfectly the loop and the thread are executed without problem since I can see messages sent by both. But, also it doesn't works at all, because the thread is propertly started but the loop reach the half of the execution and then it looks to be blocked, there are no messages are received every 5 seconds. 

One possibility is that using the same ssh session will end in a "Deadlock" problem, but since it works sometimes and other ones not I'm not pretty sure.

Here's just a brief sample of what am I doing

```
class Executor
    password = "1234"
    def self.exec_command(ssh, command)
        ch = ssh.open_channel do |channel|
           channel.on_data do |channel, data|
               if data =~ /^\[sudo\] password for /
                   # Send the password
                   channel.send_data password+"\n"
               else
                   result += data.to_s
               end
           end
            ...
            puts "Executing #{command}"
            channel.exec command
            channel.wait
            ...
        end
        ch.wait
        ch.close
        puts "Command terminated"
        return result
    end

    def self.start(host,user)
        Net::SSH.start(host,user) do |ssh|
             t = Thread.new {exec_command(ssh, "LARGE COMMAND")}
             t.join
             # Timeout set for 45 minutes
             timeout_in_seconds = 60*45
             time_start = Time.now
             loop do
                  is_terminated = exec_command(ssh, "CHECK STATUS COMMAND")
                  breack if (is_terminated == "yes")
                  time_running = Time.now - time_start 
                  if (time_running.to_i >= timeout_in_seconds)
                      puts "Timeout"
                      return
                  end
                  sleep 5
                  puts "After sleep"
             end
        end
    end
end
```
