### ISSUE TITLE
Connection hangs during algorithm initialization

### ISSUE THREAD

**Issue by mmb** [net-ssh/net-ssh#550]
Tell us what should happen

The failed connection should time out and close.

Tell us what happens instead.

Connection gets stuck and uses a lot of CPU.

netstat shows that it is in ESTABLISHED state.

strace shows the processing spinning on:

```
[pid 57774] select(35, [34], NULL, NULL, {0, 0}) = 0 (Timeout)
```

Ruby backtrace:

```
net-ssh-4.2.0/lib/net/ssh/ruby_compat.rb:20:in `select'
net-ssh-4.2.0/lib/net/ssh/ruby_compat.rb:20:in `io_select'
net-ssh-4.2.0/lib/net/ssh/transport/packet_stream.rb:75:in `available_for_read?'
net-ssh-4.2.0/lib/net/ssh/transport/packet_stream.rb:90:in `next_packet'
net-ssh-4.2.0/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
net-ssh-4.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
net-ssh-4.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
net-ssh-4.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
net-ssh-4.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
net-ssh-4.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
net-ssh-4.2.0/lib/net/ssh/transport/session.rb:88:in `initialize'
net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
```

### System configuration

- net-ssh version 4.2.0
- Ruby version 2.3.1p112

### Example App

I am passing timeout=15 and keepalive=true to Net::SSH.start.

Is there any way to make Net:SSH time out during this part of session creation?

**Comment by mmb** [comment]
I can see how this code in `transport/packet_stream.rb` could get stuck calling select in a loop forever. If there is an error it will never be available for read. Should this select use the third `error_array` parameter to handling pending exceptions?

```ruby
    # Returns true if the IO is available for reading, and false otherwise.
    def available_for_read?
      result = Net::SSH::Compat.io_select([self], nil, nil, 0)
      result && result.first.any?
    end

    # Returns the next full packet. If the mode parameter is :nonblock (the
    # default), then this will return immediately, whether a packet is
    # available or not, and will return nil if there is no packet ready to be
    # returned. If the mode parameter is :block, then this method will block
    # until a packet is available.
    def next_packet(mode=:nonblock)
      case mode
      when :nonblock then
        packet = poll_next_packet
        return packet if packet

        if available_for_read?
          if fill <= 0
            result = poll_next_packet
            if result.nil?
              raise Net::SSH::Disconnect, "connection closed by remote host"
            else
              return result
            end
          end
        end
        poll_next_packet
```

**Comment by mmb** [comment]
After looking into this a little it seems like the `IO.select` in Algorithms needs to use a timeout like the one in ServerVersion.

**Comment by lemsx1** [comment]
I've been seeing this with previous versions of net-ssh all the way to the latest 4.2. In a tcp dump for a normal connection it shows when algorithms are chosen and it continues. With net-ssh it simply stops and timeout.
If you do it enough times, sometimes it works depending on the timeout chosen and when was your last request, but it appears to be random. I could not get it to work consistently or reproduce the problem consistently.

ssh client from the command line works every time.

It's worth noting that I'm doing this against ssh implementations on HP iLO and Dell iDRAC (out of band management).

Hopefully that helps solve this. Let me know if you need more details.

**Comment by mmb** [comment]
Thank you for the helpful response.

**Comment by Lande24** [comment]
I'm experiencing a similar issue, and I've been able to consistently recreate it.
This is the scenario:
1. I start an SSH connection using Net::SSH.start with a specified timeout
2. Shortly after calling Net::SSH.start, the target server that I'm connecting to, shuts down
3. The program hangs forever on Net::SSH.start

I've explored this issue and found a solution.
After adding verbose logging to this scenario I noticed that the program hangs on the call to IO.select in PacketStream#next_packet which is called with the mode = :block. [(This Line)](https://github.com/net-ssh/net-ssh/blob/dd28fb0acac528f9d61f985f3669bc15a24c6a6a/lib/net/ssh/transport/packet_stream.rb#L109)

`result = IO.select([self]) or next`

The problem is that IO.select is called with no timeout. The socket was opened while the remote server was still up so it is in the ESTABLISHED state, but no data will ever be received on it since the remote server is down. Therefore the call to select will hang forever (it blocks until new data is received on the socket - which will never happen).

My solution is to add a :connection_timeout attribute to PacketStream and send that timeout to IO.select. Then if it returns nil (which means it timed out), I raise a ConnectionTimeout error.

I'll open a pull request with this solution and link it here soon.

**Comment by mfazekas** [comment]
If ssh server closes the tcp socket `select` should signal a read event on that socket. Calling read should return EOF, so i'm not sure if adding timeout to `select`  is the proper solution.

A script to reproduce it would be great, even if it does reproduce in 1 out of a few runs.
We have a test case that does closes the connection - https://github.com/net-ssh/net-ssh/blob/master/test/integration/test_forward.rb#L241 
That one is testing forwardning but we should be do the something like that for the ssh connection itself.

**Comment by Lande24** [comment]
The server doesn't close the connection if it crashes. I don't currently have a script that reproduces this, but I've been able to manually reproduce this simply by calling start, then shutting down the server shortly after. If you test it you'll see that it reproduces.

**Comment by mmb** [comment]
Is there any plan to add a timeout for this? I can take a stab at a PR.
