### ISSUE TITLE
Ruby version dependency

### ISSUE THREAD

**Issue by MarkMT** [net-ssh/net-ssh#606]
Something in the last 40 hours seems to have changed the Ruby version dependency to 2.2.6. I get the following error from `bundle update`, which I ran without problem less than 2 days ago -

```
Gem::InstallError: net-ssh requires Ruby version >= 2.2.6.
An error occurred while installing net-ssh (5.0.0), and Bundler cannot continue.
Make sure that `gem install net-ssh -v '5.0.0'` succeeds before bundling.

In Gemfile:
  rvm-capistrano was resolved to 1.5.6, which depends on
    capistrano was resolved to 2.15.9, which depends on
      net-scp was resolved to 1.2.1, which depends on
        net-ssh
```
The resolved version of net-scp above is the same as the last time I ran update, and there have been no changes to that gem in several weeks.

The readme says current releases require Ruby 2.0 or later. That seems to be inaccurate.

**Comment by mfazekas** [comment]
There was a net-ssh 5.0 release and net-ssh 5.0 does require ruby 2.2.6 or older, which more than reasonable given all ruby 2.2 is already EOL since march. 

Unfortunately `net-scp` does not have version lock on `net-ssh`, i'll try to release a new version. So for now the workaround is pinning down `net-ssh` to `< 5.0` in your gemfile.

**Comment by MarkMT** [comment]
Thanks. That's what I've done.
