### ISSUE TITLE
Bug in net ssh 6.0.2 works in 6.0.0 related to hmac_client algorithm

### ISSUE THREAD

**Issue by mariuz** [net-ssh/net-ssh#763]
### Expected behavior

Client shoud connect like the previous version 6.0.0 

### Actual behavior

Exception while executing as host ...  could not settle on hmac_client algorithm

Server hmac_client preferences: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
Client hmac_client preferences: hmac-sha2-512,hmac-sha2-256,hmac-sha1

### System configuration

- net-ssh version 6.0.2
- Ruby version 2.6.6

**Comment by fwininger** [comment]
According the changelog : https://github.com/net-ssh/net-ssh/blob/master/CHANGES.txt#L17

> Make sha2-{256,512}-etm@openssh.com MAC opt-in as they seems to have issues [#757]

etm algorithm has been disabled by default because there a bug in the implementation. You need to enable this algs if you want use it.

You can also use 6.1.0 version that enable this algs by default.

> Make sha2-{256,512}-etm@openssh.com MAC default again [#761]

We are very sorry for this issues :(
